### PR TITLE
Added testProfile to describe version of solidity

### PR DESCRIPTION
**Pull request by jimni1222**
## Proposed changes

This PR introduces testProfile.json file to describe version of solidity.

If there is another idea with file name, please tell me :)

## Types of changes

Please put an x in the boxes related to your change.

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] Others

## Checklist

*Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code.*

- [x] I have read the [CONTRIBUTING GUIDELINES](https://github.com/klaytn/klaytn-integration-tests/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/klaytn/klaytn-integration-tests)
- [ ] Lint and unit tests pass locally with my changes (`$ make test`)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Related issues

- Please leave the issue numbers or links related to this PR here.

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by jimni1222** [comment]
@nogang testProfile.json file is added :)

**Comment by kjhman21** [comment]
What about adding it into https://github.com/klaytn/klaytn-integration-tests/blob/master/env.template.json?

**Comment by jimni1222** [comment]
> What about adding it into https://github.com/klaytn/klaytn-integration-tests/blob/master/env.template.json?

Initially the solidity version was described in env.template.json though, now that is described in seperate file.
Because the env.template.json file is a template that allows user to set the values user use and the solidity version is not a value that user can set, but an environment(?) that should be used according to TC.

cc @nogang

**Comment by kjhman21** [comment]
@jimni1222 Ok. I got it.
Then, please change the file name. `conf.json`? `test.json`? `package.json`?

**Comment by jimni1222** [comment]
@kjhman21 @nogang 
The file name is edited to "conf.json" :)

**Comment by kjhman21** [comment]
@nogang Please share your opinion.

**Comment by nogang** [comment]
It seems to be appropriate to configure.@kjhman21 @jimni1222

**Pull request merged**
